/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package back;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Naser
 */
public class ExpiredProducts extends javax.swing.JDialog {

    DBConnection con;
    /**
     * Creates new form ExpiredProducts
     */
    // connect to the data base if there is no connection stay in the mainface so from the main face make this but now you do not have

    JFrame f;
    Date date;

    public ExpiredProducts(JFrame f) {
        super(f, true);
        con = new DBConnection();
        date = new Date();
        initComponents();
    }

    public void getExpiredProducts() throws SQLException, ClassNotFoundException {
        PreparedStatement stmt = con.getConnection().prepareStatement(" SELECT * from products where expireDate= ?", ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        String expireDate = (new SimpleDateFormat("dd-MM-yyyy").format(date));
       
        stmt.setString(1, expireDate);
        ResultSet r = stmt.executeQuery();
        try {
            if (r.next()) {
                DefaultTableModel t = (DefaultTableModel) medtable.getModel();
                for (int i = 0; i < t.getRowCount(); i--) {
                    t.removeRow(i);
                }
                while (r.next()) {
                    t.addRow(new Object[]{r.getString(2), r.getObject(4)});
                }
                medtable.setModel(t);
                medtable.validate();
                stmt.close();
            } else {
                DefaultTableModel t = (DefaultTableModel) medtable.getModel();
                int numrows = t.getRowCount();
                for (int i = numrows - 1; i >= 0; i--) {
                    t.removeRow(i);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(ExpiredProducts.this, "Error in Database", "Error Message", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    private ExpiredProducts() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        medtable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "best_price", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());

        medtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product_Name", "Expired_day"
            }
        ));
        medtable.setAutoscrolls(false);
        jScrollPane2.setViewportView(medtable);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel2.getAccessibleContext().setAccessibleName("Expired_Products");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable medtable;
    // End of variables declaration//GEN-END:variables
}
